- name: Install Apache
  pacman:
    name: apache
    state: present

- name: Start Apache service
  service:
    name: httpd
    state: started
    enabled: True

- name: Check Apache version
  command: httpd -v
  register: apache_version
  change_when: false

- name: Display Apache version
  debug:
    msg: "{{ apache_version.stdout }}"