---
- name: add MariaDB repository
  yum_repository:
    name: MariaDB
    description: MariaDB repository
    file: MariaDB
    baseurl: https://dlm.mariadb.com/repo/mariadb-server/{{ version_MariaDB }}/yum/rhel/$releasever/$basearch
    gpgkey: https://downloads.mariadb.com/MariaDB/RPM-GPG-KEY-MariaDB
    gpgcheck: yes
    module_hotfixes: 1 # Need for AlmaLinux 8

- name: Install MariaDB
  dnf:
    name:
      - MariaDB-server
      - MariaDB-client
    state: latest
    update_cache: yes

- name: Install extension
  dnf:
    name:
      - python3-PyMySQL
    state: present

- name: Start and enable MariaDB service
  service:
    name: mariadb
    state: started
    enabled: true

- name: Check MariaDB version
  command: mariadb --version
  register: mariadb_version
  changed_when: false

- name: Display MariaDB version
  debug:
    msg: "{{ mariadb_version.stdout }}"

- name: Ensure MariaDB is running
  block:
    - name: Start and enable MariaDB service
      service:
        name: mariadb
        state: started
        enabled: true
  rescue:
    - name: Notify about MariaDB service failure
      debug:
        msg: "Failed to start MariaDB service. Please check logs."
