---
- name: Deploy LAMP 
  hosts: all
  become: True
  roles:
    - { role: update_os, tags: ['update'] }                       #Обновление ОС
    - { role: apache, tags: ['apache'] }                          #Установка Apache
    - { role: mariadb, version_MariaDB: 11.5, tags: ['mariadb'] } #Установка MariaDB
    - { role: php, php_version: 8.2, tags: ['php'] }              #Установка PHP