---
- name: Ensure system is upgraded
  block:
    - name: Upgrade system
      shell: "pacman -Syu --noconfirm"
      become: yes
  rescue:
    - name: Notify about upgrade failure
      debug:
        msg: "Failed to upgrade the system. Please check logs."

- name: Check system version
  shell: "pacman -Q"
  register: pacman_output
  changed_when: false

- name: Display installed packages
  debug:
    msg: "{{ pacman_output.stdout }}"