- name: Ensure system is upgraded
  block:
    - name: Update all packages
      dnf:
        name: "*"
        state: latest
  rescue:
    - name: Notify about upgrade failure
      debug:
        msg: "Failed to upgrade the system. Please check logs."

- name: Check if a reboot is needed
  shell: "needs-restarting -r"
  register: reboot_required
  ignore_errors: yes
  changed_when: false

- name: Reboot the box if needed
  reboot:
    msg: "Reboot initiated by Ansible for system updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required.rc != 0