---
- name: Deploy NextCloud 
  hosts: all
  become: True
  roles:
    - update_os
    - apache
    - { role: php, php_version: 8.3, php_modules: "{{ php_module }}", php_memory_limit: 512M  } 
    - { role: mariadb, version_MariaDB: 11.5, secure_install: False, create_db: True, create_user: True, db_name: nextcloud_db, db_user: nextcloud_user}

  tasks:

    - name: Disable Selinux on RHEL-like
      block:

        - name: Disable SELinux
          selinux:
            state: disabled
          register: selinux_status

        - name: Reboot host
          reboot:
            reboot_timeout: 3600
          when: selinux_status.changed
      when: ansible_os_family == "RedHat"

    - name: Download NextCloud
      get_url:
        url: "https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.zip"
        dest: "/tmp/nextcloud.zip"
      register: download

    - name: Set Nextcloud
      block:

        - name: Unzip Nextcloud
          unarchive:
            src: /tmp/nextcloud.zip
            dest: /var/www/
            remote_src: yes
            owner: apache
            group: apache

        - name: Create data directory
          file:
            path: /var/www/nextcloud/data
            state: directory
            owner: apache
            group: apache

      when: download.changed

    - name: Config Apache for NextCloud
      template:
        src: nextcloud.conf
        dest: /etc/httpd/conf.d/nextcloud.conf
      notify: Restart apache


  handlers:
    - name: Restart apache
      service:
        name: httpd
        state: restarted

