- name: Install PHP on Debian/Ubuntu
  apt:
    name: "php{{ php_version | default('') }}"
    state: present
    update_cache: yes
  notify: Restart web server

- name: Install PHP-modules
  apt:
    name: "{{ php_modules }}"
    state: present
  when: 
    - php_modules is defined
    - php_modules | length > 0
  notify: Restart web server

- name: Check PHP version
  command: php -v
  register: php_ver_check
  changed_when: false
  ignore_errors: yes

- name: Display PHP version
  debug:
    msg: "PHP version: {{ php_ver_check.stdout_lines | first }}"