---
- name: Deploy Mattermost 
  hosts: all
  become: True
  roles:
    - update_os
    - { role: mariadb, version_MariaDB: 10.5, secure_install: False, create_db: True, create_user: True }

  tasks:

    - name: Disable Selinux on RHEL-like
      block:

        - name: Disable SELinux
          selinux:
            state: disabled
          register: selinux_status

        - name: Reboot host
          reboot:
            reboot_timeout: 3600
          when: selinux_status.changed
      
      when: ansible_os_family == "RedHat"

    - name: Add user mattermost
      user:
        name: mattermost
        state: present
        system: True
        create_home: false

    - name: Download mattermost version {{ mattermost_version }}
      get_url:
        url: "https://releases.mattermost.com/{{ mattermost_version }}/mattermost-enterprise-{{ mattermost_version }}-linux-amd64.tar.gz"
        dest: "/tmp/mattermost.tar.gz"
      register: download

    - name: Config mattermost
      block:

        - name: Extract mattermost from archive 
          unarchive:
            src: /tmp/mattermost.tar.gz
            dest: /opt/
            remote_src: yes

        - name: Make dir for data
          file:
            path: /opt/mattermost/data
            state: directory
            owner: mattermost
            group: mattermost
      
        - name: Set owner for mattermost directory
          file:
            path: /opt/mattermost/
            owner: mattermost
            group: mattermost
            mode: g+w
            recurse: True

        - name: Set parametr DriverName
          lineinfile: 
            dest: /opt/mattermost/config/config.json
            regexp: '"DriverName": "postgres",'
            line: '    "DriverName": "mysql",'

        - name: Set parametr DataSource
          lineinfile:
            path: /opt/mattermost/config/config.json
            regexp: '"DataSource":'
            line: '    "DataSource": "mattermost:{{ db_user_pass }}@tcp(127.0.0.1:3306)/mattermost?charset=utf8mb4,utf8\u0026readTimeout=30s\u0026writeTimeout=30s",'
    
      when: download.changed

    - name: Create unit for mattermost
      template:
        src: mattermost.service
        dest: /etc/systemd/system/mattermost.service

    - name: Start and enable Mattermost service
      service:
        name: mattermost
        state: started
        enabled: True

      
  

