---
- name: Deploy Joomla 
  hosts: all
  become: True
  roles:
    - update_os
    - apache
    - { role: php, php_modules: "{{ php_module }}" } 
    - { role: mariadb, secure_install: False, create_db: True, create_user: True, }

  tasks:

    - name: Download Joomla
      get_url:
        url: "https://downloads.joomla.org/cms/joomla5/{{ joomla_version }}/Joomla_{{ joomla_version }}-Stable-Full_Package.zip"
        dest: "/tmp/joomla.zip"
      register: download

    - name: Make dir for joomla
      file:
        path: /var/www/html/joomla
        state: directory
        owner: "{{ owner_apache }}"
        group: "{{ owner_apache }}"

    - name: Unzip Joomla
      unarchive:
        src: /tmp/joomla.zip
        dest: /var/www/html/joomla
        remote_src: yes
        owner: "{{ owner_apache }}"
        group: "{{ owner_apache }}"
      when: download.changed

    - name: Activate Virtual Host Joomla
      shell: a2ensite joomla.conf
      when: ansible_os_family == "Debian" and download.changed

    - name: Config Apache for Joomla
      template: 
        src: joomla.conf
        dest: "{{ work_dir_apache }}"
      notify: Restart apache

    - name: Secure install for RHEL-like
      block:

        - name: Open port in firewalld
          firewalld:
            service: http
            state: enabled
            permanent: True
          register: firewall

        - name: Reload firewall
          service:
            name: firewalld
            state: reloaded
          when: firewall is changed
        
        - name: Disable SELinux
          selinux:
            state: disabled
          register: selinux
        
        - name: Reboot host
          reboot:
            msg: "Reboot for apply SELinux settings"
            connect_timeout: 5
            reboot_timeout: 300
          when: selinux is changed

      when: ansible_os_family == "RedHat"

  handlers:
    - name: Restart apache
      service:
        name: "{{ apache_service }}"
        state: restarted